title: Descargá Somos FPD
description: >-
  Disfrutá de la mejor App de fútbol con los mejores periodistas Argentinos, descargála yá en Android o en iOS


plugins:
- jekyll-archives
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate